# Generated by Django 2.1.7 on 2019-02-20 22:19

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('ingredients', tinymce.models.HTMLField()),
                ('steps', tinymce.models.HTMLField()),
                ('notes', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
