# Generated by Django 2.1.7 on 2019-04-11 20:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
